{% set version = '0.2.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-intrinsic
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/intRinsic_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/intRinsic/intRinsic_{{ version }}.tar.gz
  sha256: efc2468da25dbc24aaceabd937f9dc44ffb5dcd751524a3622ceb588fd0d7a88

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-fnn
    - r-mcmcpack
    - r-rcpp
    - r-rcpparmadillo
    - r-dplyr
    - r-ggplot2
    - r-knitr
    - r-latex2exp
    - r-reshape2
    - r-rlang
    - r-salso
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-fnn
    - r-mcmcpack
    - r-rcpp
    - r-rcpparmadillo
    - r-dplyr
    - r-ggplot2
    - r-knitr
    - r-latex2exp
    - r-reshape2
    - r-rlang
    - r-salso

test:
  commands:
    - $R -e "library('intRinsic')"           # [not win]
    - "\"%R%\" -e \"library('intRinsic')\""  # [win]

about:
  home: https://github.com/Fradenti/intRinsic
  license: MIT
  summary: 'Provides functions to estimate the intrinsic dimension of a dataset via likelihood-based
    approaches. Specifically, the package implements the ''TWO-NN'' and ''Gride'' estimators
    and the ''Hidalgo'' Bayesian mixture model. In addition, the first reference contains
    an extended vignette on the usage of the ''TWO-NN'' and ''Hidalgo'' models. References:
    Denti (2022+, <arXiv:2102.11425>); Allegra et al. (2020, <doi:10.1038/s41598-020-72222-0>);
    Denti et al. (2022, <doi:10.1038/s41598-022-20991-1>); Facco et al. (2017, <doi:10.1038/s41598-017-11873-y>);
    Santos-Fernandez et al. (2021, <doi:10.1038/s41598-022-20991-1>).'
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - leej3

# Package: intRinsic
# Title: Likelihood-Based Intrinsic Dimension Estimators
# Version: 0.2.2
# Authors@R: c( person("Francesco", "Denti", ,"francescodenti.personal@gmail.com", role = c("aut", "cre", "cph"), comment = c(ORCID = "0000-0003-2978-4702")), person("Andrea", "Gilardi", ,"andrea.gilardi@unimib.it", role = "aut", comment = c(ORCID = "0000-0002-9424-7439")) )
# Maintainer: Francesco Denti <francescodenti.personal@gmail.com>
# Description: Provides functions to estimate the intrinsic dimension of a dataset via likelihood-based approaches. Specifically, the package implements the 'TWO-NN' and 'Gride' estimators and the 'Hidalgo' Bayesian mixture model. In addition, the first reference contains an extended vignette on the usage of the 'TWO-NN' and 'Hidalgo' models. References: Denti (2022+, <arXiv:2102.11425>); Allegra et al. (2020, <doi:10.1038/s41598-020-72222-0>); Denti et al. (2022, <doi:10.1038/s41598-022-20991-1>); Facco et al. (2017, <doi:10.1038/s41598-017-11873-y>); Santos-Fernandez et al. (2021, <doi:10.1038/s41598-022-20991-1>).
# License: MIT + file LICENSE
# URL: https://github.com/Fradenti/intRinsic
# BugReports: https://github.com/fradenti/intRinsic/issues
# Depends: R (>= 4.2.0)
# Imports: dplyr, FNN, ggplot2, knitr, latex2exp, MCMCpack, Rcpp, reshape2, rlang, salso, stats, utils
# LinkingTo: Rcpp, RcppArmadillo
# NeedsCompilation: yes
# ByteCompile: true
# Encoding: UTF-8
# RoxygenNote: 7.2.2
# Suggests: covr
# Packaged: 2022-12-18 07:51:04 UTC; francescodenti
# Author: Francesco Denti [aut, cre, cph] (<https://orcid.org/0000-0003-2978-4702>), Andrea Gilardi [aut] (<https://orcid.org/0000-0002-9424-7439>)
# Repository: CRAN
# Date/Publication: 2022-12-18 08:10:02 UTC
